### ISSUE TITLE
Add please pgagent extension

### ISSUE THREAD

**Issue by ygorigor** [ivanlonel/postgis-with-extensions#17]
Hello,

Can you add also pgagent extension to potgreslq images?

Thanks.

**Comment by ivanlonel** [comment]
Hey @ygorigor!

I'm sorry for taking so long to answer. I was in the middle of a trip when I saw your issue, but when I got back you had already closed it and I completely forgot about it. 😅

I added pgagent in my latest update. I hadn't added it before because, since I use pg_cron, I never used pgagent and I thought it was something that ran on the client side only.

Thanks for the suggestion.
